name: designhub_monorepo
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  analyzer: ^6.4.1
  cli_progress_bar: ^1.0.4

dev_dependencies:
  flutter_lints: ^2.0.1
  melos: ^3.4.0
