name: main_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_app:
  shared_main:
  html: ^0.15.4
  url_launcher: ^6.2.5
  svg_flutter: ^0.0.1

dev_dependencies:
  build_runner: ^2.4.8
  auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true
  fonts:
    - family: Cygre
      fonts:
        - asset: packages/shared_app/fonts/Cygre/Cygre-Thin.ttf
          weight: 100
        - asset: packages/shared_app/fonts/Cygre/Cygre-ThinIt.ttf
          weight: 100
          style: italic
        - asset: packages/shared_app/fonts/Cygre/Cygre-Light.ttf
          weight: 300
        - asset: packages/shared_app/fonts/Cygre/Cygre-LightIt.ttf
          weight: 300
          style: italic
        - asset: packages/shared_app/fonts/Cygre/Cygre-Regular.ttf
          weight: 400
        - asset: packages/shared_app/fonts/Cygre/Cygre-RegularIt.ttf
          weight: 400
          style: italic
        - asset: packages/shared_app/fonts/Cygre/Cygre-Medium.ttf
          weight: 500
        - asset: packages/shared_app/fonts/Cygre/Cygre-MediumIt.ttf
          weight: 500
          style: italic
        - asset: packages/shared_app/fonts/Cygre/Cygre-SemiBold.ttf
          weight: 600
        - asset: packages/shared_app/fonts/Cygre/Cygre-SemiBoldIt.ttf
          weight: 600
          style: italic
        - asset: packages/shared_app/fonts/Cygre/Cygre-Bold.ttf
          weight: 700
        - asset: packages/shared_app/fonts/Cygre/Cygre-BoldIt.ttf
          weight: 700
          style: italic
        - asset: packages/shared_app/fonts/Cygre/Cygre-ExtraBold.ttf
          weight: 800
        - asset: packages/shared_app/fonts/Cygre/Cygre-ExtraBoldIt.ttf
          weight: 800
          style: italic
        - asset: packages/shared_app/fonts/Cygre/Cygre-Black.ttf
          weight: 900
        - asset: packages/shared_app/fonts/Cygre/Cygre-BlackIt.ttf
          weight: 900
          style: italic
